In [264]:
import pandas as pd
import numpy as np
import pickle

In [266]:
df = pickle.load(open('dataset_level2.pkl', 'rb'))

In [268]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,venue
0,2,Australia,Sri Lanka,0.1,0,0,NaN,Melbourne Cricket Ground
1,2,Australia,Sri Lanka,0.2,0,0,NaN,Melbourne Cricket Ground
2,2,Australia,Sri Lanka,0.3,1,0,NaN,Melbourne Cricket Ground
3,2,Australia,Sri Lanka,0.4,2,0,NaN,Melbourne Cricket Ground
4,2,Australia,Sri Lanka,0.5,0,0,NaN,Melbourne Cricket Ground
...,...,...,...,...,...,...,...,...
115320,964,Sri Lanka,Australia,19.3,1,0,Colombo,R Premadasa Stadium
115321,964,Sri Lanka,Australia,19.4,0,0,Colombo,R Premadasa Stadium
115322,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,R Premadasa Stadium
115323,964,Sri Lanka,Australia,19.6,2,0,Colombo,R Premadasa Stadium
115324,964,Sri Lanka,Australia,19.7,1,0,Colombo,R Premadasa Stadium

In [270]:
#batting_team
#bowling_team
#city
#current_score
#ball_left
#wickets_left
#crr
#last_five
#Total

In [272]:
df.isnull().sum()

match_id               0
batting_team           0
bowling_team           0
ball                   0
runs                   0
player_dismissed       0
city                8548
venue                  0
dtype: int64

In [274]:
df['city'].isnull()

0          True
1          True
2          True
3          True
4          True
          ...
115320    False
115321    False
115322    False
115323    False
115324    False
Name: city, Length: 63888, dtype: bool

In [276]:
 df[df['city'].isnull()]['venue'].value_counts()

venue
Dubai International Cricket Stadium        2969
Pallekele International Cricket Stadium    2066
Melbourne Cricket Ground                   1453
Sydney Cricket Ground                       749
Adelaide Oval                               498
Harare Sports Club                          372
Sharjah Cricket Stadium                     249
Sylhet International Cricket Stadium        128
Carrara Oval                                 64
Name: count, dtype: int64

In [278]:
 df[df['city'].isnull()]['venue'].unique()

array(['Melbourne Cricket Ground', 'Adelaide Oval',
       'Dubai International Cricket Stadium', 'Sydney Cricket Ground',
       'Sylhet International Cricket Stadium', 'Harare Sports Club',
       'Carrara Oval', 'Pallekele International Cricket Stadium',
       'Sharjah Cricket Stadium'], dtype=object)

In [280]:
np.where(df['city'].isnull(), df['venue'].str.split().apply(lambda x:x[0]),df['city'])

array(['Melbourne', 'Melbourne', 'Melbourne', ..., 'Colombo', 'Colombo',
       'Colombo'], dtype=object)

In [282]:
cities = np.where(df['city'].isnull(), df['venue'].str.split().apply(lambda x:x[0]),df['city'])

In [284]:
df['city'] = cities

In [286]:
df.isnull().sum()

match_id            0
batting_team        0
bowling_team        0
ball                0
runs                0
player_dismissed    0
city                0
venue               0
dtype: int64

In [288]:
df.drop(columns=['venue'], inplace=True)

In [290]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne
...,...,...,...,...,...,...,...
115320,964,Sri Lanka,Australia,19.3,1,0,Colombo
115321,964,Sri Lanka,Australia,19.4,0,0,Colombo
115322,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo
115323,964,Sri Lanka,Australia,19.6,2,0,Colombo
115324,964,Sri Lanka,Australia,19.7,1,0,Colombo

In [292]:
df['city'].value_counts()

city
Colombo          4086
Mirpur           3420
Johannesburg     3331
Dubai            2969
Auckland         2532
                 ...
Nairobi           123
Potchefstroom     122
Dharamsala        122
Ahmedabad         121
Carrara            64
Name: count, Length: 86, dtype: int64

In [294]:
df['city'].value_counts()[df['city'].value_counts() > 600]

city
Colombo            4086
Mirpur             3420
Johannesburg       3331
Dubai              2969
Auckland           2532
Cape Town          2369
London             2106
Pallekele          2066
Barbados           2050
Sydney             1579
Melbourne          1574
Durban             1520
St Lucia           1487
Wellington         1350
Lauderhill         1238
Hamilton           1219
Centurion          1189
Manchester         1144
Abu Dhabi          1099
Mumbai              995
Nottingham          991
Southampton         987
Mount Maunganui     938
Chittagong          868
Kolkata             844
Lahore              748
Delhi               739
Nagpur              735
Chandigarh          627
Adelaide            623
Bangalore           620
St Kitts            618
Cardiff             615
Christchurch        614
Trinidad            611
Name: count, dtype: int64

In [296]:
df['city'].value_counts()[df['city'].value_counts() > 600].shape

(35,)

In [298]:
df['city'].value_counts()[df['city'].value_counts() > 600].sum()

50501

In [300]:
eligable_cities = df['city'].value_counts()[df['city'].value_counts() > 600].index.tolist()

In [302]:
df = df[df['city'].isin(eligable_cities)]

In [304]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne
...,...,...,...,...,...,...,...
115320,964,Sri Lanka,Australia,19.3,1,0,Colombo
115321,964,Sri Lanka,Australia,19.4,0,0,Colombo
115322,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo
115323,964,Sri Lanka,Australia,19.6,2,0,Colombo
115324,964,Sri Lanka,Australia,19.7,1,0,Colombo

In [306]:
df['match_id'] = pd.to_numeric(df['match_id'], errors='coerce')  # Attempt conversion, handle errors

C:\Users\Sateesh\AppData\Local\Temp\ipykernel_35320\3051239587.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['match_id'] = pd.to_numeric(df['match_id'], errors='coerce')  # Attempt conversion, handle errors

In [308]:
df.isnull().sum()

match_id            0
batting_team        0
bowling_team        0
ball                0
runs                0
player_dismissed    0
city                0
dtype: int64

In [310]:
df.groupby('match_id')['runs'].cumsum()

0           0
1           0
2           1
3           3
4           3
         ...
115320    125
115321    125
115322    125
115323    127
115324    128
Name: runs, Length: 50501, dtype: int64

In [312]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50501 entries, 0 to 115324
Data columns (total 7 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   match_id          50501 non-null  int64
 1   batting_team      50501 non-null  object
 2   bowling_team      50501 non-null  object
 3   ball              50501 non-null  float64
 4   runs              50501 non-null  int64
 5   player_dismissed  50501 non-null  object
 6   city              50501 non-null  object
dtypes: float64(1), int64(2), object(4)
memory usage: 3.1+ MB

In [314]:
df['current_score'] = df.groupby('match_id')['runs'].cumsum()

C:\Users\Sateesh\AppData\Local\Temp\ipykernel_35320\190681986.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['current_score'] = df.groupby('match_id')['runs'].cumsum()

In [316]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,0
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,0
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,1
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,3
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,3
...,...,...,...,...,...,...,...,...
115320,964,Sri Lanka,Australia,19.3,1,0,Colombo,125
115321,964,Sri Lanka,Australia,19.4,0,0,Colombo,125
115322,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,125
115323,964,Sri Lanka,Australia,19.6,2,0,Colombo,127
115324,964,Sri Lanka,Australia,19.7,1,0,Colombo,128

In [318]:
df['over'] = df['ball'].apply(lambda x:str(x).split(".")[0])
df['ball_no'] = df['ball'].apply(lambda x:str(x).split(".")[1])
df

C:\Users\Sateesh\AppData\Local\Temp\ipykernel_35320\2777558413.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['over'] = df['ball'].apply(lambda x:str(x).split(".")[0])
C:\Users\Sateesh\AppData\Local\Temp\ipykernel_35320\2777558413.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ball_no'] = df['ball'].apply(lambda x:str(x).split(".")[1])

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,0,0,1
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,0,0,2
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,1,0,3
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,3,0,4
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,3,0,5
...,...,...,...,...,...,...,...,...,...,...
115320,964,Sri Lanka,Australia,19.3,1,0,Colombo,125,19,3
115321,964,Sri Lanka,Australia,19.4,0,0,Colombo,125,19,4
115322,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,125,19,5
115323,964,Sri Lanka,Australia,19.6,2,0,Colombo,127,19,6
115324,964,Sri Lanka,Australia,19.7,1,0,Colombo,128,19,7

In [320]:
df['balls_bowled'] = (df['over'].astype('int')*6) + df['ball_no'].astype('int')
df

C:\Users\Sateesh\AppData\Local\Temp\ipykernel_35320\562775579.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_bowled'] = (df['over'].astype('int')*6) + df['ball_no'].astype('int')

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,0,0,1,1
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,0,0,2,2
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,1,0,3,3
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,3,0,4,4
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,3,0,5,5
...,...,...,...,...,...,...,...,...,...,...,...
115320,964,Sri Lanka,Australia,19.3,1,0,Colombo,125,19,3,117
115321,964,Sri Lanka,Australia,19.4,0,0,Colombo,125,19,4,118
115322,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,125,19,5,119
115323,964,Sri Lanka,Australia,19.6,2,0,Colombo,127,19,6,120
115324,964,Sri Lanka,Australia,19.7,1,0,Colombo,128,19,7,121

In [322]:
df['balls_left'] = 120 - df['balls_bowled']
df['balls_left'] = df['balls_left'].apply(lambda x:0 if x<0 else x)
df

C:\Users\Sateesh\AppData\Local\Temp\ipykernel_35320\2304996896.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_left'] = 120 - df['balls_bowled']
C:\Users\Sateesh\AppData\Local\Temp\ipykernel_35320\2304996896.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['balls_left'] = df['balls_left'].apply(lambda x:0 if x<0 else x)

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,0,0,1,1,119
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,0,0,2,2,118
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,1,0,3,3,117
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,3,0,4,4,116
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,3,0,5,5,115
...,...,...,...,...,...,...,...,...,...,...,...,...
115320,964,Sri Lanka,Australia,19.3,1,0,Colombo,125,19,3,117,3
115321,964,Sri Lanka,Australia,19.4,0,0,Colombo,125,19,4,118,2
115322,964,Sri Lanka,Australia,19.5,0,DM de Silva,Colombo,125,19,5,119,1
115323,964,Sri Lanka,Australia,19.6,2,0,Colombo,127,19,6,120,0
115324,964,Sri Lanka,Australia,19.7,1,0,Colombo,128,19,7,121,0

In [324]:
df['player_dismissed'] = df['player_dismissed'].apply(lambda x:0 if x=='0' else 1)

C:\Users\Sateesh\AppData\Local\Temp\ipykernel_35320\739840433.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['player_dismissed'] = df['player_dismissed'].apply(lambda x:0 if x=='0' else 1)

In [326]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,0,0,1,1,119
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,0,0,2,2,118
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,1,0,3,3,117
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,3,0,4,4,116
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,3,0,5,5,115
...,...,...,...,...,...,...,...,...,...,...,...,...
115320,964,Sri Lanka,Australia,19.3,1,0,Colombo,125,19,3,117,3
115321,964,Sri Lanka,Australia,19.4,0,0,Colombo,125,19,4,118,2
115322,964,Sri Lanka,Australia,19.5,0,1,Colombo,125,19,5,119,1
115323,964,Sri Lanka,Australia,19.6,2,0,Colombo,127,19,6,120,0
115324,964,Sri Lanka,Australia,19.7,1,0,Colombo,128,19,7,121,0

In [328]:
df['player_dismissed'] = df.groupby('match_id')['player_dismissed'].cumsum()

C:\Users\Sateesh\AppData\Local\Temp\ipykernel_35320\2543326779.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['player_dismissed'] = df.groupby('match_id')['player_dismissed'].cumsum()

In [330]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,0,0,1,1,119
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,0,0,2,2,118
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,1,0,3,3,117
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,3,0,4,4,116
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,3,0,5,5,115
...,...,...,...,...,...,...,...,...,...,...,...,...
115320,964,Sri Lanka,Australia,19.3,1,8,Colombo,125,19,3,117,3
115321,964,Sri Lanka,Australia,19.4,0,8,Colombo,125,19,4,118,2
115322,964,Sri Lanka,Australia,19.5,0,9,Colombo,125,19,5,119,1
115323,964,Sri Lanka,Australia,19.6,2,9,Colombo,127,19,6,120,0
115324,964,Sri Lanka,Australia,19.7,1,9,Colombo,128,19,7,121,0

In [332]:

df['wickets_left'] = 10 - df['player_dismissed']

C:\Users\Sateesh\AppData\Local\Temp\ipykernel_35320\4260449721.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['wickets_left'] = 10 - df['player_dismissed']

In [334]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left,wickets_left
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,0,0,1,1,119,10
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,0,0,2,2,118,10
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,1,0,3,3,117,10
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,3,0,4,4,116,10
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,3,0,5,5,115,10
...,...,...,...,...,...,...,...,...,...,...,...,...,...
115320,964,Sri Lanka,Australia,19.3,1,8,Colombo,125,19,3,117,3,2
115321,964,Sri Lanka,Australia,19.4,0,8,Colombo,125,19,4,118,2,2
115322,964,Sri Lanka,Australia,19.5,0,9,Colombo,125,19,5,119,1,1
115323,964,Sri Lanka,Australia,19.6,2,9,Colombo,127,19,6,120,0,1
115324,964,Sri Lanka,Australia,19.7,1,9,Colombo,128,19,7,121,0,1

In [336]:
df['crr'] = (df['current_score']*6)/df['balls_bowled']

C:\Users\Sateesh\AppData\Local\Temp\ipykernel_35320\914577034.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['crr'] = (df['current_score']*6)/df['balls_bowled']

In [338]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left,wickets_left,crr
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,0,0,1,1,119,10,0.000000
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,0,0,2,2,118,10,0.000000
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,1,0,3,3,117,10,2.000000
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,3,0,4,4,116,10,4.500000
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,3,0,5,5,115,10,3.600000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115320,964,Sri Lanka,Australia,19.3,1,8,Colombo,125,19,3,117,3,2,6.410256
115321,964,Sri Lanka,Australia,19.4,0,8,Colombo,125,19,4,118,2,2,6.355932
115322,964,Sri Lanka,Australia,19.5,0,9,Colombo,125,19,5,119,1,1,6.302521
115323,964,Sri Lanka,Australia,19.6,2,9,Colombo,127,19,6,120,0,1,6.350000
115324,964,Sri Lanka,Australia,19.7,1,9,Colombo,128,19,7,121,0,1,6.347107

In [342]:
groups = df.groupby('match_id')

match_ids = df['match_id'].unique()
last_five = []
for id in match_ids:
    last_five.extend(groups.get_group(id).rolling(window=30)['runs'].sum().values.tolist())

In [346]:
df['last_five'] = last_five

C:\Users\Sateesh\AppData\Local\Temp\ipykernel_35320\1595651733.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['last_five'] = last_five

In [348]:
df

,match_id,batting_team,bowling_team,ball,runs,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left,wickets_left,crr,last_five
0,2,Australia,Sri Lanka,0.1,0,0,Melbourne,0,0,1,1,119,10,0.000000,NaN
1,2,Australia,Sri Lanka,0.2,0,0,Melbourne,0,0,2,2,118,10,0.000000,NaN
2,2,Australia,Sri Lanka,0.3,1,0,Melbourne,1,0,3,3,117,10,2.000000,NaN
3,2,Australia,Sri Lanka,0.4,2,0,Melbourne,3,0,4,4,116,10,4.500000,NaN
4,2,Australia,Sri Lanka,0.5,0,0,Melbourne,3,0,5,5,115,10,3.600000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115320,964,Sri Lanka,Australia,19.3,1,8,Colombo,125,19,3,117,3,2,6.410256,32.0
115321,964,Sri Lanka,Australia,19.4,0,8,Colombo,125,19,4,118,2,2,6.355932,32.0
115322,964,Sri Lanka,Australia,19.5,0,9,Colombo,125,19,5,119,1,1,6.302521,32.0
115323,964,Sri Lanka,Australia,19.6,2,9,Colombo,127,19,6,120,0,1,6.350000,33.0
115324,964,Sri Lanka,Australia,19.7,1,9,Colombo,128,19,7,121,0,1,6.347107,32.0

In [356]:
#

df.groupby('match_id')['runs'].sum().reset_index().merge(df, on='match_id')

,match_id,runs_x,batting_team,bowling_team,ball,runs_y,player_dismissed,city,current_score,over,ball_no,balls_bowled,balls_left,wickets_left,crr,last_five
0,2,168,Australia,Sri Lanka,0.1,0,0,Melbourne,0,0,1,1,119,10,0.000000,NaN
1,2,168,Australia,Sri Lanka,0.2,0,0,Melbourne,0,0,2,2,118,10,0.000000,NaN
2,2,168,Australia,Sri Lanka,0.3,1,0,Melbourne,1,0,3,3,117,10,2.000000,NaN
3,2,168,Australia,Sri Lanka,0.4,2,0,Melbourne,3,0,4,4,116,10,4.500000,NaN
4,2,168,Australia,Sri Lanka,0.5,0,0,Melbourne,3,0,5,5,115,10,3.600000,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
50496,964,128,Sri Lanka,Australia,19.3,1,8,Colombo,125,19,3,117,3,2,6.410256,32.0
50497,964,128,Sri Lanka,Australia,19.4,0,8,Colombo,125,19,4,118,2,2,6.355932,32.0
50498,964,128,Sri Lanka,Australia,19.5,0,9,Colombo,125,19,5,119,1,1,6.302521,32.0
50499,964,128,Sri Lanka,Australia,19.6,2,9,Colombo,127,19,6,120,0,1,6.350000,33.0
50500,964,128,Sri Lanka,Australia,19.7,1,9,Colombo,128,19,7,121,0,1,6.347107,32.0

In [358]:
 final_df = df.groupby('match_id')['runs'].sum().reset_index().merge(df, on='match_id')

In [364]:
final_df = final_df[['batting_team','bowling_team','city','current_score','balls_left','wickets_left','crr','last_five','runs_x']]

In [366]:
final_df

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five,runs_x
0,Australia,Sri Lanka,Melbourne,0,119,10,0.000000,NaN,168
1,Australia,Sri Lanka,Melbourne,0,118,10,0.000000,NaN,168
2,Australia,Sri Lanka,Melbourne,1,117,10,2.000000,NaN,168
3,Australia,Sri Lanka,Melbourne,3,116,10,4.500000,NaN,168
4,Australia,Sri Lanka,Melbourne,3,115,10,3.600000,NaN,168
...,...,...,...,...,...,...,...,...,...
50496,Sri Lanka,Australia,Colombo,125,3,2,6.410256,32.0,128
50497,Sri Lanka,Australia,Colombo,125,2,2,6.355932,32.0,128
50498,Sri Lanka,Australia,Colombo,125,1,1,6.302521,32.0,128
50499,Sri Lanka,Australia,Colombo,127,0,1,6.350000,33.0,128
50500,Sri Lanka,Australia,Colombo,128,0,1,6.347107,32.0,128

In [368]:
final_df.isnull().sum()

batting_team         0
bowling_team         0
city                 0
current_score        0
balls_left           0
wickets_left         0
crr                  0
last_five        12024
runs_x               0
dtype: int64

In [370]:
final_df.dropna(inplace=True)

C:\Users\Sateesh\AppData\Local\Temp\ipykernel_35320\2709626079.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_df.dropna(inplace=True)

In [372]:
final_df.isnull().sum()

batting_team     0
bowling_team     0
city             0
current_score    0
balls_left       0
wickets_left     0
crr              0
last_five        0
runs_x           0
dtype: int64

In [374]:
final_df.sample(final_df.shape[0])

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five,runs_x
32309,West Indies,England,Pallekele,118,42,9,9.076923,45.0,179
3857,New Zealand,West Indies,Mount Maunganui,205,16,7,11.826923,62.0,243
8033,New Zealand,India,Auckland,103,44,6,8.131579,53.0,158
45656,New Zealand,Sri Lanka,Mount Maunganui,135,23,7,8.350515,33.0,182
6229,Sri Lanka,Bangladesh,Colombo,157,2,3,7.983051,59.0,159
...,...,...,...,...,...,...,...,...,...
31297,India,Afghanistan,Colombo,69,58,7,6.677419,35.0,159
47528,South Africa,Afghanistan,Mumbai,93,58,8,9.000000,32.0,209
49538,India,Bangladesh,Mirpur,127,20,6,7.620000,53.0,166
8182,New Zealand,India,Hamilton,167,22,7,10.224490,55.0,212
47499,South Africa,Afghanistan,Mumbai,62,87,9,11.272727,54.0,209

In [376]:
final_df = final_df.sample(final_df.shape[0])

In [379]:
final_df

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five,runs_x
46813,New Zealand,India,Nagpur,72,42,6,5.538462,30.0,126
23656,Australia,Pakistan,Melbourne,68,67,7,7.698113,38.0,127
16877,Australia,Pakistan,Johannesburg,134,25,6,8.463158,43.0,164
11791,England,Australia,Southampton,106,40,6,7.950000,37.0,162
34991,India,Sri Lanka,Pallekele,129,19,7,7.663366,37.0,155
...,...,...,...,...,...,...,...,...,...
21787,Sri Lanka,West Indies,London,45,82,10,7.105263,41.0,158
39994,Australia,West Indies,Mirpur,75,67,7,8.490566,40.0,178
20447,Sri Lanka,West Indies,Nottingham,84,68,10,9.692308,48.0,192
34540,South Africa,India,Johannesburg,48,89,9,9.290323,44.0,219
40254,South Africa,England,Chittagong,86,59,10,8.459016,39.0,196

In [381]:
final_df.sample(2)

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five,runs_x
29856,Australia,India,Melbourne,104,28,5,6.782609,32.0,131
36527,Sri Lanka,Australia,Melbourne,47,72,7,5.875000,32.0,161

In [385]:
X = final_df.drop(columns = ['runs_x'])
y = final_df['runs_x']

In [387]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size = 0.2, random_state=1)

In [389]:
X_train.head()

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five
3625,Sri Lanka,India,Colombo,84,65,7,9.163636,38.0
3029,Pakistan,West Indies,Trinidad,45,79,8,6.585366,33.0
9368,Sri Lanka,Australia,Melbourne,50,73,8,6.382979,30.0
46688,South Africa,Sri Lanka,Cape Town,99,46,9,8.027027,40.0
4207,Pakistan,New Zealand,Mount Maunganui,106,37,7,7.662651,40.0

In [391]:
y_train.head(2)

3625    170
3029    137
Name: runs_x, dtype: int64

In [393]:
X_test.head(2)

,batting_team,bowling_team,city,current_score,balls_left,wickets_left,crr,last_five
24261,South Africa,Afghanistan,Barbados,69,67,8,7.811321,30.0
35496,New Zealand,South Africa,Durban,86,14,1,4.867925,24.0

In [395]:
y_test.head(2)

24261    139
35496     86
Name: runs_x, dtype: int64

In [401]:
len(X_train)

30781

In [403]:
len(X_test)

7696

In [405]:
len(y_train)

30781

In [409]:
!pip install xgboost

Defaulting to user installation because normal site-packages is not writeable
Collecting xgboost
  Downloading xgboost-2.1.1-py3-none-win_amd64.whl.metadata (2.1 kB)
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from xgboost) (1.26.4)
Requirement already satisfied: scipy in c:\programdata\anaconda3\lib\site-packages (from xgboost) (1.13.1)
Downloading xgboost-2.1.1-py3-none-win_amd64.whl (124.9 MB)
   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/124.9 MB 435.7 kB/s eta 0:04:47
   ---------------------------------------- 0.1/124.9 MB 1.2 MB/s eta 0:01:45
   ---------------------------------------- 0.5/124.9 MB 3.3 MB/s eta 0:00:39
   ---------------------------------------- 0.8/124.9 MB 4.5 MB/s eta 0:00:28
   ---------------------------------------- 1.0/124.9 MB 4.3 MB/s eta 0:00:29
   ---------------------------------------- 1.2/124.9 MB 4.3 MB/s eta 0:00:30
   ---------------------------------------- 1.2/124.9 MB 4.3 MB/s eta 0:00:30
   ---------------------------------------- 1.2/124.9 MB 4.3 MB/s eta 0:00:30
   ---------------------------------------- 1.2/124.9 MB 4.3 MB/s eta 0:00:30
   ---------------------------------------- 1.2/124.9 MB 4.3 MB/s eta 0:00:30
    --------------------------------------- 1.9/124.9 MB 3.6 MB/s eta 0:00:35
    --------------------------------------- 2.1/124.9 MB 3.6 MB/s eta 0:00:34
    --------------------------------------- 2.3/124.9 MB 3.7 MB/s eta 0:00:33
    --------------------------------------- 2.5/124.9 MB 3.7 MB/s eta 0:00:33
    --------------------------------------- 2.7/124.9 MB 3.7 MB/s eta 0:00:34
    --------------------------------------- 2.8/124.9 MB 3.7 MB/s eta 0:00:33
    --------------------------------------- 2.8/124.9 MB 3.7 MB/s eta 0:00:33
    --------------------------------------- 2.8/124.9 MB 3.7 MB/s eta 0:00:33
    --------------------------------------- 3.0/124.9 MB 3.3 MB/s eta 0:00:38
    --------------------------------------- 3.1/124.9 MB 3.4 MB/s eta 0:00:36
   - -------------------------------------- 3.2/124.9 MB 3.2 MB/s eta 0:00:38
   - -------------------------------------- 3.4/124.9 MB 3.3 MB/s eta 0:00:37
   - -------------------------------------- 3.6/124.9 MB 3.3 MB/s eta 0:00:37
   - -------------------------------------- 3.6/124.9 MB 3.2 MB/s eta 0:00:38
   - -------------------------------------- 3.7/124.9 MB 3.1 MB/s eta 0:00:39
   - -------------------------------------- 4.2/124.9 MB 3.5 MB/s eta 0:00:35
   - -------------------------------------- 4.4/124.9 MB 3.4 MB/s eta 0:00:36
   - -------------------------------------- 4.6/124.9 MB 3.5 MB/s eta 0:00:35
   - -------------------------------------- 4.7/124.9 MB 3.5 MB/s eta 0:00:35
   - -------------------------------------- 4.7/124.9 MB 3.5 MB/s eta 0:00:35
   - -------------------------------------- 4.7/124.9 MB 3.5 MB/s eta 0:00:35
   - -------------------------------------- 5.0/124.9 MB 3.4 MB/s eta 0:00:36
   - -------------------------------------- 5.5/124.9 MB 3.5 MB/s eta 0:00:34
   - -------------------------------------- 5.7/124.9 MB 3.5 MB/s eta 0:00:34
   - -------------------------------------- 5.9/124.9 MB 3.6 MB/s eta 0:00:34
   - -------------------------------------- 6.1/124.9 MB 3.6 MB/s eta 0:00:34
   - -------------------------------------- 6.2/124.9 MB 3.6 MB/s eta 0:00:34
   -- ------------------------------------- 6.4/124.9 MB 3.6 MB/s eta 0:00:33
   -- ------------------------------------- 6.6/124.9 MB 3.6 MB/s eta 0:00:34
   -- ------------------------------------- 6.8/124.9 MB 3.6 MB/s eta 0:00:33
   -- ------------------------------------- 7.0/124.9 MB 3.6 MB/s eta 0:00:33
   -- ------------------------------------- 7.2/124.9 MB 3.6 MB/s eta 0:00:33
   -- ------------------------------------- 7.4/124.9 MB 3.6 MB/s eta 0:00:33
   -- ------------------------------------- 7.6/124.9 MB 3.6 MB/s eta 0:00:33
   -- ------------------------------------- 7.8/124.9 MB 3.6 MB/s eta 0:00:33
   -- ------------------------------------- 8.0/124.9 MB 3.6 MB/s eta 0:00:33
   -- ------------------------------------- 8.1/124.9 MB 3.6 MB/s eta 0:00:33
   -- ------------------------------------- 8.3/124.9 MB 3.7 MB/s eta 0:00:32
   -- ------------------------------------- 8.5/124.9 MB 3.7 MB/s eta 0:00:32
   -- ------------------------------------- 8.7/124.9 MB 3.7 MB/s eta 0:00:32
   -- ------------------------------------- 8.9/124.9 MB 3.7 MB/s eta 0:00:32
   -- ------------------------------------- 9.0/124.9 MB 3.7 MB/s eta 0:00:32
   -- ------------------------------------- 9.3/124.9 MB 3.7 MB/s eta 0:00:32
   --- ------------------------------------ 9.4/124.9 MB 3.7 MB/s eta 0:00:32
   --- ------------------------------------ 9.6/124.9 MB 3.7 MB/s eta 0:00:32
   --- ------------------------------------ 9.8/124.9 MB 3.7 MB/s eta 0:00:32
   --- ------------------------------------ 10.0/124.9 MB 3.7 MB/s eta 0:00:32
   --- ------------------------------------ 10.2/124.9 MB 3.7 MB/s eta 0:00:32
   --- ------------------------------------ 10.4/124.9 MB 3.8 MB/s eta 0:00:31
   --- ------------------------------------ 10.5/124.9 MB 3.8 MB/s eta 0:00:31
   --- ------------------------------------ 10.7/124.9 MB 3.7 MB/s eta 0:00:31
   --- ------------------------------------ 10.9/124.9 MB 3.7 MB/s eta 0:00:31
   --- ------------------------------------ 11.1/124.9 MB 3.7 MB/s eta 0:00:32
   --- ------------------------------------ 11.3/124.9 MB 3.7 MB/s eta 0:00:32
   --- ------------------------------------ 11.5/124.9 MB 3.9 MB/s eta 0:00:29
   --- ------------------------------------ 11.7/124.9 MB 3.8 MB/s eta 0:00:30
   --- ------------------------------------ 11.7/124.9 MB 3.8 MB/s eta 0:00:30
   --- ------------------------------------ 11.7/124.9 MB 3.8 MB/s eta 0:00:30
   --- ------------------------------------ 12.0/124.9 MB 3.7 MB/s eta 0:00:31
   --- ------------------------------------ 12.5/124.9 MB 3.7 MB/s eta 0:00:31
   ---- ----------------------------------- 12.6/124.9 MB 3.7 MB/s eta 0:00:31
   ---- ----------------------------------- 12.8/124.9 MB 3.7 MB/s eta 0:00:31
   ---- ----------------------------------- 13.0/124.9 MB 3.7 MB/s eta 0:00:31
   ---- ----------------------------------- 13.2/124.9 MB 3.9 MB/s eta 0:00:29
   ---- ----------------------------------- 13.4/124.9 MB 3.9 MB/s eta 0:00:29
   ---- ----------------------------------- 13.6/124.9 MB 3.9 MB/s eta 0:00:29
   ---- ----------------------------------- 13.8/124.9 MB 3.9 MB/s eta 0:00:29
   ---- ----------------------------------- 13.9/124.9 MB 4.0 MB/s eta 0:00:28
   ---- ----------------------------------- 14.1/124.9 MB 4.0 MB/s eta 0:00:28
   ---- ----------------------------------- 14.3/124.9 MB 3.9 MB/s eta 0:00:29
   ---- ----------------------------------- 14.5/124.9 MB 3.9 MB/s eta 0:00:29
   ---- ----------------------------------- 14.7/124.9 MB 3.9 MB/s eta 0:00:29
   ---- ----------------------------------- 14.9/124.9 MB 3.9 MB/s eta 0:00:29
   ---- ----------------------------------- 15.1/124.9 MB 4.1 MB/s eta 0:00:28
   ---- ----------------------------------- 15.2/124.9 MB 4.0 MB/s eta 0:00:28
   ---- ----------------------------------- 15.4/124.9 MB 4.0 MB/s eta 0:00:28
   ----- ---------------------------------- 15.7/124.9 MB 3.9 MB/s eta 0:00:29
   ----- ---------------------------------- 15.8/124.9 MB 3.9 MB/s eta 0:00:29
   ----- ---------------------------------- 16.0/124.9 MB 3.9 MB/s eta 0:00:28
   ----- ---------------------------------- 16.2/124.9 MB 3.9 MB/s eta 0:00:29
   ----- ---------------------------------- 16.4/124.9 MB 3.9 MB/s eta 0:00:29
   ----- ---------------------------------- 16.6/124.9 MB 3.9 MB/s eta 0:00:28
   ----- ---------------------------------- 16.8/124.9 MB 3.9 MB/s eta 0:00:28
   ----- ---------------------------------- 17.0/124.9 MB 3.9 MB/s eta 0:00:28
   ----- ---------------------------------- 17.1/124.9 MB 3.9 MB/s eta 0:00:28
   ----- ---------------------------------- 17.3/124.9 MB 3.9 MB/s eta 0:00:28
   ----- ---------------------------------- 17.5/124.9 MB 3.9 MB/s eta 0:00:28
   ----- ---------------------------------- 17.7/124.9 MB 3.9 MB/s eta 0:00:28
   ----- ---------------------------------- 17.9/124.9 MB 3.9 MB/s eta 0:00:28
   ----- ---------------------------------- 18.1/124.9 MB 3.9 MB/s eta 0:00:28
   ----- ---------------------------------- 18.2/124.9 MB 3.9 MB/s eta 0:00:28
   ----- ---------------------------------- 18.4/124.9 MB 3.9 MB/s eta 0:00:28
   ----- ---------------------------------- 18.6/124.9 MB 3.9 MB/s eta 0:00:28
   ------ --------------------------------- 18.8/124.9 MB 3.9 MB/s eta 0:00:28
   ------ --------------------------------- 19.0/124.9 MB 3.9 MB/s eta 0:00:28
   ------ --------------------------------- 19.1/124.9 MB 3.9 MB/s eta 0:00:28
   ------ --------------------------------- 19.3/124.9 MB 3.9 MB/s eta 0:00:28
   ------ --------------------------------- 19.5/124.9 MB 3.9 MB/s eta 0:00:28
   ------ --------------------------------- 19.7/124.9 MB 3.9 MB/s eta 0:00:27
   ------ --------------------------------- 19.9/124.9 MB 3.9 MB/s eta 0:00:27
   ------ --------------------------------- 20.1/124.9 MB 3.9 MB/s eta 0:00:27
   ------ --------------------------------- 20.3/124.9 MB 3.9 MB/s eta 0:00:27
   ------ --------------------------------- 20.4/124.9 MB 3.9 MB/s eta 0:00:27
   ------ --------------------------------- 20.6/124.9 MB 3.9 MB/s eta 0:00:27
   ------ --------------------------------- 20.8/124.9 MB 3.9 MB/s eta 0:00:27
   ------ --------------------------------- 21.0/124.9 MB 3.9 MB/s eta 0:00:27
   ------ --------------------------------- 21.2/124.9 MB 3.9 MB/s eta 0:00:27
   ------ --------------------------------- 21.4/124.9 MB 3.9 MB/s eta 0:00:27
   ------ --------------------------------- 21.6/124.9 MB 3.9 MB/s eta 0:00:27
   ------ --------------------------------- 21.8/124.9 MB 3.9 MB/s eta 0:00:27
   ------- -------------------------------- 21.9/124.9 MB 3.9 MB/s eta 0:00:27
   ------- -------------------------------- 22.1/124.9 MB 4.0 MB/s eta 0:00:26
   ------- -------------------------------- 22.3/124.9 MB 4.0 MB/s eta 0:00:26
   ------- -------------------------------- 22.5/124.9 MB 3.9 MB/s eta 0:00:26
   ------- -------------------------------- 22.7/124.9 MB 3.9 MB/s eta 0:00:27
   ------- -------------------------------- 22.8/124.9 MB 3.9 MB/s eta 0:00:27
   ------- -------------------------------- 23.0/124.9 MB 3.9 MB/s eta 0:00:27
   ------- -------------------------------- 23.2/124.9 MB 3.9 MB/s eta 0:00:27
   ------- -------------------------------- 23.4/124.9 MB 3.9 MB/s eta 0:00:27
   ------- -------------------------------- 23.6/124.9 MB 3.9 MB/s eta 0:00:26
   ------- -------------------------------- 23.8/124.9 MB 3.9 MB/s eta 0:00:27
   ------- -------------------------------- 24.0/124.9 MB 3.9 MB/s eta 0:00:26
   ------- -------------------------------- 24.2/124.9 MB 3.9 MB/s eta 0:00:26
   ------- -------------------------------- 24.3/124.9 MB 3.9 MB/s eta 0:00:26
   ------- -------------------------------- 24.5/124.9 MB 3.9 MB/s eta 0:00:26
   ------- -------------------------------- 24.7/124.9 MB 3.9 MB/s eta 0:00:26
   ------- -------------------------------- 24.9/124.9 MB 3.9 MB/s eta 0:00:26
   -------- ------------------------------- 25.1/124.9 MB 3.9 MB/s eta 0:00:26
   -------- ------------------------------- 25.3/124.9 MB 3.9 MB/s eta 0:00:26
   -------- ------------------------------- 25.5/124.9 MB 3.9 MB/s eta 0:00:26
   -------- ------------------------------- 25.6/124.9 MB 3.9 MB/s eta 0:00:26
   -------- ------------------------------- 25.8/124.9 MB 3.9 MB/s eta 0:00:26
   -------- ------------------------------- 26.0/124.9 MB 3.9 MB/s eta 0:00:26
   -------- ------------------------------- 26.2/124.9 MB 3.9 MB/s eta 0:00:26
   -------- ------------------------------- 26.4/124.9 MB 3.9 MB/s eta 0:00:26
   -------- ------------------------------- 26.6/124.9 MB 3.9 MB/s eta 0:00:26
   -------- ------------------------------- 26.7/124.9 MB 3.9 MB/s eta 0:00:26
   -------- ------------------------------- 26.9/124.9 MB 3.9 MB/s eta 0:00:26
   -------- ------------------------------- 27.1/124.9 MB 3.9 MB/s eta 0:00:26
   -------- ------------------------------- 27.2/124.9 MB 3.9 MB/s eta 0:00:26
   -------- ------------------------------- 27.4/124.9 MB 3.9 MB/s eta 0:00:26
   -------- ------------------------------- 27.6/124.9 MB 3.9 MB/s eta 0:00:25
   -------- ------------------------------- 27.8/124.9 MB 3.9 MB/s eta 0:00:26
   -------- ------------------------------- 27.9/124.9 MB 3.9 MB/s eta 0:00:26
   --------- ------------------------------ 28.1/124.9 MB 3.9 MB/s eta 0:00:25
   --------- ------------------------------ 28.3/124.9 MB 3.9 MB/s eta 0:00:25
   --------- ------------------------------ 28.5/124.9 MB 3.9 MB/s eta 0:00:25
   --------- ------------------------------ 28.7/124.9 MB 3.9 MB/s eta 0:00:25
   --------- ------------------------------ 28.9/124.9 MB 3.9 MB/s eta 0:00:25
   --------- ------------------------------ 29.1/124.9 MB 3.9 MB/s eta 0:00:25
   --------- ------------------------------ 29.2/124.9 MB 3.9 MB/s eta 0:00:25
   --------- ------------------------------ 29.4/124.9 MB 3.9 MB/s eta 0:00:25
   --------- ------------------------------ 29.6/124.9 MB 3.9 MB/s eta 0:00:25
   --------- ------------------------------ 29.7/124.9 MB 3.9 MB/s eta 0:00:25
   --------- ------------------------------ 29.9/124.9 MB 3.9 MB/s eta 0:00:25
   --------- ------------------------------ 30.1/124.9 MB 3.9 MB/s eta 0:00:25
   --------- ------------------------------ 30.3/124.9 MB 3.9 MB/s eta 0:00:25
   --------- ------------------------------ 30.4/124.9 MB 3.9 MB/s eta 0:00:25
   --------- ------------------------------ 30.6/124.9 MB 3.9 MB/s eta 0:00:25
   --------- ------------------------------ 30.8/124.9 MB 3.9 MB/s eta 0:00:25
   --------- ------------------------------ 31.0/124.9 MB 3.9 MB/s eta 0:00:25
   --------- ------------------------------ 31.2/124.9 MB 3.9 MB/s eta 0:00:25
   ---------- ----------------------------- 31.4/124.9 MB 3.9 MB/s eta 0:00:25
   ---------- ----------------------------- 31.5/124.9 MB 3.9 MB/s eta 0:00:25
   ---------- ----------------------------- 31.7/124.9 MB 3.9 MB/s eta 0:00:25
   ---------- ----------------------------- 31.9/124.9 MB 3.9 MB/s eta 0:00:25
   ---------- ----------------------------- 32.1/124.9 MB 3.9 MB/s eta 0:00:25
   ---------- ----------------------------- 32.3/124.9 MB 3.9 MB/s eta 0:00:25
   ---------- ----------------------------- 32.5/124.9 MB 3.9 MB/s eta 0:00:25
   ---------- ----------------------------- 32.6/124.9 MB 3.9 MB/s eta 0:00:24
   ---------- ----------------------------- 32.8/124.9 MB 3.9 MB/s eta 0:00:24
   ---------- ----------------------------- 33.0/124.9 MB 3.9 MB/s eta 0:00:24
   ---------- ----------------------------- 33.2/124.9 MB 3.9 MB/s eta 0:00:24
   ---------- ----------------------------- 33.4/124.9 MB 3.9 MB/s eta 0:00:24
   ---------- ----------------------------- 33.6/124.9 MB 3.9 MB/s eta 0:00:24
   ---------- ----------------------------- 33.7/124.9 MB 3.9 MB/s eta 0:00:24
   ---------- ----------------------------- 33.9/124.9 MB 3.9 MB/s eta 0:00:24
   ---------- ----------------------------- 34.1/124.9 MB 3.9 MB/s eta 0:00:24
   ---------- ----------------------------- 34.3/124.9 MB 3.9 MB/s eta 0:00:24
   ----------- ---------------------------- 34.4/124.9 MB 3.9 MB/s eta 0:00:24
   ----------- ---------------------------- 34.6/124.9 MB 3.9 MB/s eta 0:00:24
   ----------- ---------------------------- 34.8/124.9 MB 3.8 MB/s eta 0:00:24
   ----------- ---------------------------- 35.0/124.9 MB 3.8 MB/s eta 0:00:24
   ----------- ---------------------------- 35.2/124.9 MB 3.8 MB/s eta 0:00:24
   ----------- ---------------------------- 35.4/124.9 MB 3.8 MB/s eta 0:00:24
   ----------- ---------------------------- 35.6/124.9 MB 3.8 MB/s eta 0:00:24
   ----------- ---------------------------- 35.8/124.9 MB 3.9 MB/s eta 0:00:24
   ----------- ---------------------------- 36.0/124.9 MB 3.8 MB/s eta 0:00:24
   ----------- ---------------------------- 36.1/124.9 MB 3.8 MB/s eta 0:00:24
   ----------- ---------------------------- 36.3/124.9 MB 3.9 MB/s eta 0:00:24
   ----------- ---------------------------- 36.5/124.9 MB 3.8 MB/s eta 0:00:24
   ----------- ---------------------------- 36.7/124.9 MB 3.8 MB/s eta 0:00:24
   ----------- ---------------------------- 36.9/124.9 MB 3.9 MB/s eta 0:00:23
   ----------- ---------------------------- 37.1/124.9 MB 3.9 MB/s eta 0:00:23
   ----------- ---------------------------- 37.3/124.9 MB 3.9 MB/s eta 0:00:23
   ----------- ---------------------------- 37.4/124.9 MB 3.9 MB/s eta 0:00:23
   ------------ --------------------------- 37.6/124.9 MB 3.9 MB/s eta 0:00:23
   ------------ --------------------------- 37.8/124.9 MB 3.9 MB/s eta 0:00:23
   ------------ --------------------------- 38.0/124.9 MB 3.9 MB/s eta 0:00:23
   ------------ --------------------------- 38.2/124.9 MB 3.9 MB/s eta 0:00:23
   ------------ --------------------------- 38.3/124.9 MB 3.9 MB/s eta 0:00:23
   ------------ --------------------------- 38.5/124.9 MB 3.9 MB/s eta 0:00:23
   ------------ --------------------------- 38.7/124.9 MB 3.9 MB/s eta 0:00:23
   ------------ --------------------------- 38.9/124.9 MB 3.9 MB/s eta 0:00:23
   ------------ --------------------------- 39.0/124.9 MB 3.9 MB/s eta 0:00:23
   ------------ --------------------------- 39.2/124.9 MB 3.9 MB/s eta 0:00:23
   ------------ --------------------------- 39.4/124.9 MB 3.9 MB/s eta 0:00:23
   ------------ --------------------------- 39.6/124.9 MB 3.9 MB/s eta 0:00:23
   ------------ --------------------------- 39.8/124.9 MB 3.9 MB/s eta 0:00:23
   ------------ --------------------------- 39.9/124.9 MB 3.9 MB/s eta 0:00:23
   ------------ --------------------------- 40.2/124.9 MB 3.9 MB/s eta 0:00:22
   ------------ --------------------------- 40.3/124.9 MB 3.9 MB/s eta 0:00:22
   ------------ --------------------------- 40.5/124.9 MB 3.9 MB/s eta 0:00:22
   ------------- -------------------------- 40.7/124.9 MB 3.9 MB/s eta 0:00:22
   ------------- -------------------------- 40.9/124.9 MB 3.9 MB/s eta 0:00:22
   ------------- -------------------------- 41.1/124.9 MB 3.9 MB/s eta 0:00:22
   ------------- -------------------------- 41.2/124.9 MB 3.9 MB/s eta 0:00:22
   ------------- -------------------------- 41.4/124.9 MB 3.9 MB/s eta 0:00:22
   ------------- -------------------------- 41.6/124.9 MB 3.9 MB/s eta 0:00:22
   ------------- -------------------------- 41.8/124.9 MB 3.9 MB/s eta 0:00:22
   ------------- -------------------------- 42.0/124.9 MB 3.9 MB/s eta 0:00:22
   ------------- -------------------------- 42.1/124.9 MB 3.9 MB/s eta 0:00:22
   ------------- -------------------------- 42.3/124.9 MB 3.9 MB/s eta 0:00:22
   ------------- -------------------------- 42.5/124.9 MB 3.9 MB/s eta 0:00:22
   ------------- -------------------------- 42.7/124.9 MB 3.9 MB/s eta 0:00:22
   ------------- -------------------------- 42.9/124.9 MB 3.9 MB/s eta 0:00:22
   ------------- -------------------------- 43.0/124.9 MB 3.9 MB/s eta 0:00:22
   ------------- -------------------------- 43.2/124.9 MB 3.9 MB/s eta 0:00:22
   ------------- -------------------------- 43.4/124.9 MB 3.9 MB/s eta 0:00:22
   ------------- -------------------------- 43.6/124.9 MB 3.9 MB/s eta 0:00:21
   -------------- ------------------------- 43.8/124.9 MB 3.9 MB/s eta 0:00:21
   -------------- ------------------------- 44.0/124.9 MB 3.9 MB/s eta 0:00:21
   -------------- ------------------------- 44.1/124.9 MB 3.9 MB/s eta 0:00:21
   -------------- ------------------------- 44.3/124.9 MB 3.9 MB/s eta 0:00:21
   -------------- ------------------------- 44.5/124.9 MB 3.9 MB/s eta 0:00:21
   -------------- ------------------------- 44.7/124.9 MB 3.9 MB/s eta 0:00:21

In [421]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.metrics import r2_score,mean_absolute_error

In [423]:
trf = ColumnTransformer([
    ('trf',OneHotEncoder(drop='first'),['batting_team','bowling_team','city'])
]
,remainder='passthrough')

In [425]:
trf

ColumnTransformer(remainder='passthrough',
                  transformers=[('trf', OneHotEncoder(drop='first'),
                                 ['batting_team', 'bowling_team', 'city'])])

In [429]:
pipe = Pipeline(steps=[
    ('step1',trf),
    ('step2',StandardScaler(with_mean=False)),
    ('step3',XGBRegressor(n_estimators=1000,learning_rate=0.2,max_depth=12,random_state=1))
])

In [431]:
pipe.fit(X_train,y_train)
y_pred = pipe.predict(X_test)
print(r2_score(y_test,y_pred))
print(mean_absolute_error(y_test,y_pred))

0.9874076186605166
1.653735502346142

In [433]:
pickle.dump(pipe,open('pipe.pkl', 'wb'))